
resources:
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: js
  - url: /community_plugin/state-attribute-element/state-attribute-element.js
    type: js
  - url: /local/state-element.js
    type: js
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/group-element/group-element.js
    type: module
  - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/popup-card.js
    type: js
  - url: /local/card-tools.js
    type: js
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module

    
#background: center / cover no-repeat url(\"/local/images/blackwood.png\"),


title: Master Mason

views: !include_dir_merge_list views


cch:
  kiosk_mode: false
#
background: center / cover no-repeat url("/local/images/blackwood.png") fixed
    # View tab title.
 # - title: Example
  #  cards:


