- alias: At Home State
  trigger:
    - platform: state
      entity_id: input_boolean.day_mode, input_boolean.nap_mode, input_boolean.night_mode, input_boolean.sleep_mode
      from: 'off'
      to: 'on'
  action:
    service: input_boolean.turn_off
    data_template:
      entity_id: >
        {% set booleans = [ 'input_boolean.day_mode', 'input_boolean.nap_mode', 'input_boolean.night_mode', 'input_boolean.sleep_mode' ] | reject('equalto', trigger.entity_id) %}
        {{ booleans | list | join(', ') }}