- alias: Night Time
  trigger:
  - platform: sun
    event: sunset
    offset: '-01:00:00'
  condition: []
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.night_mode
    
